In [201]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [202]:
df_train = pd.read_excel('/content/Data_Train.xlsx', engine = 'openpyxl')

In [203]:
df_test = pd.read_excel('/content/Test_set.xlsx',engine='openpyxl')

In [204]:
df_train.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [205]:
df_test.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [206]:
pip install sheryanalysis==0.1.0

Requirement already satisfied: sheryanalysis==0.1.0 in /usr/local/lib/python3.12/dist-packages (0.1.0)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sheryanalysis==0.1.0) (2.2.2)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.12/dist-packages (from sheryanalysis==0.1.0) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sheryanalysis==0.1.0) (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->sheryanalysis==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->sheryanalysis==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->sheryanalysis==0.1.0) (2026.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sheryanalysis==0.1.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sheryanalysis==0.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sheryanalysis==0.1.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->sheryanalysis==0.1.0) (1.17.0)

In [207]:
import sheryanalysis as sh
sh.analyze(df_train)

🔍 Basic Analysis Report

INFO:sheryanalysis:
🔍 Basic Analysis Report

------------------------------------------------------------

INFO:sheryanalysis:------------------------------------------------------------

📏 Shape: (10683, 11)

INFO:sheryanalysis:📏 Shape: (10683, 11)

🧱 Columns: ['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops', 'Additional_Info', 'Price']

INFO:sheryanalysis:🧱 Columns: ['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops', 'Additional_Info', 'Price']

🧼 Columns with nulls: ['Route', 'Total_Stops']

INFO:sheryanalysis:
🧼 Columns with nulls: ['Route', 'Total_Stops']

🔠 Categorical Columns: ['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops', 'Additional_Info']

INFO:sheryanalysis:
🔠 Categorical Columns: ['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops', 'Additional_Info']

🔢 Numerical Columns: ['Price']

INFO:sheryanalysis:
🔢 Numerical Columns: ['Price']

📅 Datetime Columns: ['Date_of_Journey', 'Dep_Time', 'Arrival_Time']

INFO:sheryanalysis:
📅 Datetime Columns: ['Date_of_Journey', 'Dep_Time', 'Arrival_Time']

{'shape': (10683, 11),
 'columns': ['Airline',
  'Date_of_Journey',
  'Source',
  'Destination',
  'Route',
  'Dep_Time',
  'Arrival_Time',
  'Duration',
  'Total_Stops',
  'Additional_Info',
  'Price'],
 'dtypes': {'Airline': dtype('O'),
  'Date_of_Journey': dtype('O'),
  'Source': dtype('O'),
  'Destination': dtype('O'),
  'Route': dtype('O'),
  'Dep_Time': dtype('O'),
  'Arrival_Time': dtype('O'),
  'Duration': dtype('O'),
  'Total_Stops': dtype('O'),
  'Additional_Info': dtype('O'),
  'Price': dtype('int64')},
 'null_counts': {'Airline': 0,
  'Date_of_Journey': 0,
  'Source': 0,
  'Destination': 0,
  'Route': 1,
  'Dep_Time': 0,
  'Arrival_Time': 0,
  'Duration': 0,
  'Total_Stops': 1,
  'Additional_Info': 0,
  'Price': 0},
 'total_rows': 10683,
 'column_types': {'categorical': ['Airline',
   'Source',
   'Destination',
   'Route',
   'Duration',
   'Total_Stops',
   'Additional_Info'],
  'numerical': ['Price'],
  'datetime': ['Date_of_Journey', 'Dep_Time', 'Arrival_Time'],
  'text': []}}

In [208]:
df_final = pd.concat([df_train, df_test], ignore_index=True)

In [209]:
df_final

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0
...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [210]:
df_final.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [211]:
df_final.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [212]:
df_test.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
2666,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info
2667,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info
2668,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info
2669,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info
2670,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info

In [213]:
df_train.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [214]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.1+ MB

In [215]:
##Feature Engineering

In [216]:
df_final['Date'] = df_final['Date_of_Journey'].str.split('/').str[0]
df_final['Month'] = df_final['Date_of_Journey'].str.split('/').str[1]
df_final['Year'] = df_final['Date_of_Journey'].str.split('/').str[2]

In [217]:
df_final.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019

In [218]:
df_final['Date']=df_final['Date'].astype(int)
df_final['Month']=df_final['Month'].astype(int)
df_final['Year']=df_final['Year'].astype(int)

In [219]:
df_final

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN,6,6,2019
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN,27,3,2019
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN,6,3,2019
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN,6,3,2019
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN,15,6,2019

In [220]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int64
 12  Month            13354 non-null  int64
 13  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 1.4+ MB

In [221]:
df_final = df_final.drop('Date_of_Journey', axis=1)

In [222]:
df_final.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [223]:
print(type(df_final))

<class 'pandas.core.frame.DataFrame'>

In [224]:
df_final = pd.concat([df_train, df_test], ignore_index = True)

In [225]:
df_final['Date'] = df_final['Date_of_Journey'].str.split('/').str[0]
df_final['Month'] = df_final['Date_of_Journey'].str.split('/').str[1]
df_final['Year'] = df_final['Date_of_Journey'].str.split('/').str[2]

In [226]:
df_final = df_final.drop('Date_of_Journey', axis=1)

In [227]:
df_final.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019

In [228]:
df_final['Arrival_Time']=df_final['Arrival_Time'].apply(lambda x : x.split(' ')[0])

In [229]:
 df_final.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
dtype: int64

In [230]:
df_final['Arrival_hour'] = df_final['Arrival_Time'].apply(lambda x : x.split(':')[0])

In [231]:
df_final['Arrival_min'] = df_final['Arrival_Time'].apply(lambda x : x.split(':')[1])

In [232]:
df_final['Arrival_min'] = df_final['Arrival_Time'].apply(lambda x : x.split(' ')[0].split(':')[1])

In [233]:
df_final.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,03,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,06,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019,21,35

In [234]:
df_final['Arrival_hour'] = df_final['Arrival_hour'].astype(int)
df_final['Arrival_min'] = df_final['Arrival_min'].astype(int)

In [235]:
df_final = df_final.drop('Arrival_Time', axis=1)

In [236]:
df_final['Dep_hour'] = df_final['Dep_Time'].apply(lambda x : x.split(':')[0])
df_final['Dep_min'] = df_final['Dep_Time'].apply(lambda x : x.split(':')[1])
df_final = df_final.drop('Dep_Time', axis = 1)

In [237]:
df_final.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,03,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,05,2019,13,15,05,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,06,2019,4,25,09,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218.0,12,05,2019,23,30,18,05
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302.0,01,03,2019,21,35,16,50

In [238]:
df_final['Dep_hour'] = df_final['Dep_hour'].astype(int)
df_final['Dep_min'] = df_final['Dep_min'].astype(int)

In [239]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  object
 9   Month            13354 non-null  object
 10  Year             13354 non-null  object
 11  Arrival_hour     13354 non-null  int64
 12  Arrival_min      13354 non-null  int64
 13  Dep_hour         13354 non-null  int64
 14  Dep_min          13354 non-null  int64
dtypes: float64(1), int64(4), object(10)
memory usage: 1.5+ MB

In [240]:
df_final.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date', 'Month', 'Year', 'Arrival_hour',
       'Arrival_min', 'Dep_hour', 'Dep_min'],
      dtype='object')

In [241]:
df_final.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,03,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,05,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,06,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218.0,12,05,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302.0,01,03,2019,21,35,16,50

In [242]:
df_final['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [243]:
df_final['Total_Stops'].isnull().sum()

np.int64(1)

In [244]:
df_final['Total_Stops'] = df_final['Total_Stops'].map({'non-stop': 0, '2 stops':2, '1 stop':1, '3 stops':3, 'nan':1, '4 stops':4})

In [245]:
df_final.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897.0,24,03,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,No info,7662.0,1,05,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2.0,No info,13882.0,9,06,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1.0,No info,6218.0,12,05,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1.0,No info,13302.0,01,03,2019,21,35,16,50

In [246]:
df_final.drop('Route',axis=1,inplace = True)
df_final.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,03,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,05,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,06,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,05,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,01,03,2019,21,35,16,50

In [247]:
df_final['Date'] = df_final['Date'].astype(int)
df_final['Month'] = df_final['Month'].astype(int)
df_final['Year'] = df_final['Year'].astype(int)
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  object
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_hour     13354 non-null  int64
 11  Arrival_min      13354 non-null  int64
 12  Dep_hour         13354 non-null  int64
 13  Dep_min          13354 non-null  int64
dtypes: float64(2), int64(7), object(5)
memory usage: 1.4+ MB

In [248]:
df_final['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [249]:
df_final['Duration'].unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m',
       '20h 30m', '3h 45m', '31h 10m', '40h 40m', '22h 50m', '32h 25m'],
      dtype=object)

In [250]:
df_final['Dur_hour'] = df_final['Duration'].str.split(' ').str[0].str.split('h').str[0]

df_final['Dur_min'] = df_final['Duration'].str.split(' ').str[1].str.split('m').str[0]


df_final.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,Dur_hour,Dur_min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [251]:
df_final

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,Dur_hour,Dur_min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,Kolkata,Banglore,23h 55m,1.0,No info,NaN,6,6,2019,20,25,20,30,23,55
13350,IndiGo,Kolkata,Banglore,2h 35m,0.0,No info,NaN,27,3,2019,16,55,14,20,2,35
13351,Jet Airways,Delhi,Cochin,6h 35m,1.0,No info,NaN,6,3,2019,4,25,21,50,6,35
13352,Air India,Delhi,Cochin,15h 15m,1.0,No info,NaN,6,3,2019,19,15,4,0,15,15
13353,Multiple carriers,Delhi,Cochin,14h 20m,1.0,No info,NaN,15,6,2019,19,15,4,55,14,20

In [254]:
df_final['Dur_hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '5m', '41', '40'], dtype=object)

In [255]:
df_final.drop(6474,axis = 0, inplace = True)
df_final.drop(2660,axis = 0, inplace = True)

In [256]:
df_final[df_final['Dur_hour'] == '5m']

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,Dur_hour,Dur_min
13343,Air India,Mumbai,Hyderabad,5m,2.0,No info,NaN,12,3,2019,16,55,16,50,5m,NaN

In [257]:
df_final.drop(13343,axis = 0, inplace = True)

In [258]:
df_final[df_final['Dur_hour'] == '5m']

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_hour, Arrival_min, Dep_hour, Dep_min, Dur_hour, Dur_min]
Index: []

In [259]:
import numpy as np
original_price_data = pd.concat([df_train['Price'], pd.Series([np.nan] * len(df_test), dtype=float)], ignore_index=True)
df_final['Price'] = original_price_data.loc[df_final.index]
df_final['Price'] = df_final['Price'].replace(np.nan, 0)
df_final['Price'].unique()

array([ 3897.,  7662., 13882., ..., 12352., 12648.,     0.])

In [260]:
df_final['Dur_min'].unique()

array(['50', '25', nan, '45', '30', '5', '15', '35', '10', '20', '55',
       '40'], dtype=object)

In [261]:
df_final['Dur_hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '41', '40'], dtype=object)

In [262]:
df_final['Dur_min'] = df_final['Dur_min'].map({'NaN':0,'nan':0})

In [263]:
df_final['Price'] = df_final['Price'].replace(np.nan, 0)

In [264]:
df_final['Price'].astype(int)

0         3897
1         7662
2        13882
3         6218
4        13302
         ...
13349        0
13350        0
13351        0
13352        0
13353        0
Name: Price, Length: 13351, dtype: int64

In [265]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13351 entries, 0 to 13353
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13351 non-null  object
 1   Source           13351 non-null  object
 2   Destination      13351 non-null  object
 3   Duration         13351 non-null  object
 4   Total_Stops      13350 non-null  float64
 5   Additional_Info  13351 non-null  object
 6   Price            13351 non-null  float64
 7   Date             13351 non-null  int64
 8   Month            13351 non-null  int64
 9   Year             13351 non-null  int64
 10  Arrival_hour     13351 non-null  int64
 11  Arrival_min      13351 non-null  int64
 12  Dep_hour         13351 non-null  int64
 13  Dep_min          13351 non-null  int64
 14  Dur_hour         13351 non-null  object
 15  Dur_min          0 non-null      float64
dtypes: float64(3), int64(7), object(6)
memory usage: 1.7+ MB

In [266]:
df_final.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,Dur_hour,Dur_min
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,NaN
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,NaN
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,NaN
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,NaN
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,NaN

In [267]:
df_final['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [268]:
df_final['Source'].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [269]:
df_final['Destination'].unique()

array(['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad'],
      dtype=object)

In [270]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df_final= pd.get_dummies(df_final,columns = ['Airline'],drop_first = True)

In [271]:
Airline_col =['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet']

In [272]:
airline_dummy_cols = [col for col in df_final.columns if col.startswith('Airline_')]
df_final[airline_dummy_cols] = df_final[airline_dummy_cols].astype(int)

In [273]:
df_final

,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,...,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,Airline_Vistara,Airline_Vistara Premium economy
0,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,...,0,1,0,0,0,0,0,0,0,0
1,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,...,0,0,0,0,0,0,0,0,0,0
2,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,...,0,0,1,0,0,0,0,0,0,0
3,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,...,0,1,0,0,0,0,0,0,0,0
4,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,Kolkata,Banglore,23h 55m,1.0,No info,0.0,6,6,2019,20,...,0,0,0,0,0,0,0,0,0,0
13350,Kolkata,Banglore,2h 35m,0.0,No info,0.0,27,3,2019,16,...,0,1,0,0,0,0,0,0,0,0
13351,Delhi,Cochin,6h 35m,1.0,No info,0.0,6,3,2019,4,...,0,0,1,0,0,0,0,0,0,0
13352,Delhi,Cochin,15h 15m,1.0,No info,0.0,6,3,2019,19,...,0,0,0,0,0,0,0,0,0,0
13353,Delhi,Cochin,14h 20m,1.0,No info,0.0,15,6,2019,19,...,0,0,0,0,1,0,0,0,0,0

In [274]:
df_final = pd.get_dummies(df_final, columns = ['Source'], drop_first= True)

In [275]:
source_dummy_cols = [col for col in df_final.columns if col.startswith('Source')]
df_final[source_dummy_cols] = df_final[source_dummy_cols].astype(int)

In [276]:
df_final

,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,...,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,Airline_Vistara,Airline_Vistara Premium economy,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai
0,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,...,0,0,0,0,0,0,0,0,0,0
1,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,...,0,0,0,0,0,0,0,0,1,0
2,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,...,0,0,0,0,0,0,0,1,0,0
3,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,...,0,0,0,0,0,0,0,0,1,0
4,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,Banglore,23h 55m,1.0,No info,0.0,6,6,2019,20,25,...,0,0,0,0,0,0,0,0,1,0
13350,Banglore,2h 35m,0.0,No info,0.0,27,3,2019,16,55,...,0,0,0,0,0,0,0,0,1,0
13351,Cochin,6h 35m,1.0,No info,0.0,6,3,2019,4,25,...,0,0,0,0,0,0,0,1,0,0
13352,Cochin,15h 15m,1.0,No info,0.0,6,3,2019,19,15,...,0,0,0,0,0,0,0,1,0,0
13353,Cochin,14h 20m,1.0,No info,0.0,15,6,2019,19,15,...,1,0,0,0,0,0,0,1,0,0

In [277]:
df_final = pd.get_dummies(df_final, columns = ['Destination'], drop_first= True)

In [278]:
destination_dummy_cols = [col for col in df_final.columns if col.startswith('Destination')]
df_final[destination_dummy_cols] = df_final[destination_dummy_cols].astype(int)

In [279]:
df_final

,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,...,Airline_Vistara Premium economy,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,...,0,0,0,0,0,0,0,0,0,1
1,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,...,0,0,0,1,0,0,0,0,0,0
2,19h,2.0,No info,13882.0,9,6,2019,4,25,9,...,0,0,1,0,0,1,0,0,0,0
3,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,...,0,0,0,1,0,0,0,0,0,0
4,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,23h 55m,1.0,No info,0.0,6,6,2019,20,25,20,...,0,0,0,1,0,0,0,0,0,0
13350,2h 35m,0.0,No info,0.0,27,3,2019,16,55,14,...,0,0,0,1,0,0,0,0,0,0
13351,6h 35m,1.0,No info,0.0,6,3,2019,4,25,21,...,0,0,1,0,0,1,0,0,0,0
13352,15h 15m,1.0,No info,0.0,6,3,2019,19,15,4,...,0,0,1,0,0,1,0,0,0,0
13353,14h 20m,1.0,No info,0.0,15,6,2019,19,15,4,...,0,0,1,0,0,1,0,0,0,0

In [280]:
df_final.shape

(13351, 33)

In [281]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13351 entries, 0 to 13353
Data columns (total 33 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Duration                                   13351 non-null  object
 1   Total_Stops                                13350 non-null  float64
 2   Additional_Info                            13351 non-null  object
 3   Price                                      13351 non-null  float64
 4   Date                                       13351 non-null  int64
 5   Month                                      13351 non-null  int64
 6   Year                                       13351 non-null  int64
 7   Arrival_hour                               13351 non-null  int64
 8   Arrival_min                                13351 non-null  int64
 9   Dep_hour                                   13351 non-null  int64
 10  Dep_min                                    13351 non-null  int64
 11  Dur_hour                                   13351 non-null  object
 12  Dur_min                                    0 non-null      float64
 13  Airline_Air India                          13351 non-null  int64
 14  Airline_GoAir                              13351 non-null  int64
 15  Airline_IndiGo                             13351 non-null  int64
 16  Airline_Jet Airways                        13351 non-null  int64
 17  Airline_Jet Airways Business               13351 non-null  int64
 18  Airline_Multiple carriers                  13351 non-null  int64
 19  Airline_Multiple carriers Premium economy  13351 non-null  int64
 20  Airline_SpiceJet                           13351 non-null  int64
 21  Airline_Trujet                             13351 non-null  int64
 22  Airline_Vistara                            13351 non-null  int64
 23  Airline_Vistara Premium economy            13351 non-null  int64
 24  Source_Chennai                             13351 non-null  int64
 25  Source_Delhi                               13351 non-null  int64
 26  Source_Kolkata                             13351 non-null  int64
 27  Source_Mumbai                              13351 non-null  int64
 28  Destination_Cochin                         13351 non-null  int64
 29  Destination_Delhi                          13351 non-null  int64
 30  Destination_Hyderabad                      13351 non-null  int64
 31  Destination_Kolkata                        13351 non-null  int64
 32  Destination_New Delhi                      13351 non-null  int64
dtypes: float64(3), int64(27), object(3)
memory usage: 3.5+ MB

In [282]:
df_final['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [283]:
df_final = pd.get_dummies(df_final, columns=['Additional_Info'], drop_first=True)

In [284]:
df_final.drop('Additional_Info', axis=1, inplace=True)

KeyError: "['Additional_Info'] not found in axis"

In [286]:
df_final['Additional_Info'] = df_final['Additional_Info'].astype(int)

KeyError: 'Additional_Info'

In [285]:
df_final

,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,...,Destination_New Delhi,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,2h 50m,0.0,3897.0,24,3,2019,1,10,22,20,...,1,False,False,False,False,False,False,False,True,False
1,7h 25m,2.0,7662.0,1,5,2019,13,15,5,50,...,0,False,False,False,False,False,False,False,True,False
2,19h,2.0,13882.0,9,6,2019,4,25,9,25,...,0,False,False,False,False,False,False,False,True,False
3,5h 25m,1.0,6218.0,12,5,2019,23,30,18,5,...,0,False,False,False,False,False,False,False,True,False
4,4h 45m,1.0,13302.0,1,3,2019,21,35,16,50,...,1,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,23h 55m,1.0,0.0,6,6,2019,20,25,20,30,...,0,False,False,False,False,False,False,False,True,False
13350,2h 35m,0.0,0.0,27,3,2019,16,55,14,20,...,0,False,False,False,False,False,False,False,True,False
13351,6h 35m,1.0,0.0,6,3,2019,4,25,21,50,...,0,False,False,False,False,False,False,False,True,False
13352,15h 15m,1.0,0.0,6,3,2019,19,15,4,0,...,0,False,False,False,False,False,False,False,True,False
13353,14h 20m,1.0,0.0,15,6,2019,19,15,4,55,...,0,False,False,False,False,False,False,False,True,False

In [287]:
bool_cols = df_final.select_dtypes(include='bool').columns

df_final[bool_cols] = df_final[bool_cols].astype(int)

In [288]:
df_final

,Duration,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,...,Destination_New Delhi,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,2h 50m,0.0,3897.0,24,3,2019,1,10,22,20,...,1,0,0,0,0,0,0,0,1,0
1,7h 25m,2.0,7662.0,1,5,2019,13,15,5,50,...,0,0,0,0,0,0,0,0,1,0
2,19h,2.0,13882.0,9,6,2019,4,25,9,25,...,0,0,0,0,0,0,0,0,1,0
3,5h 25m,1.0,6218.0,12,5,2019,23,30,18,5,...,0,0,0,0,0,0,0,0,1,0
4,4h 45m,1.0,13302.0,1,3,2019,21,35,16,50,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,23h 55m,1.0,0.0,6,6,2019,20,25,20,30,...,0,0,0,0,0,0,0,0,1,0
13350,2h 35m,0.0,0.0,27,3,2019,16,55,14,20,...,0,0,0,0,0,0,0,0,1,0
13351,6h 35m,1.0,0.0,6,3,2019,4,25,21,50,...,0,0,0,0,0,0,0,0,1,0
13352,15h 15m,1.0,0.0,6,3,2019,19,15,4,0,...,0,0,0,0,0,0,0,0,1,0
13353,14h 20m,1.0,0.0,15,6,2019,19,15,4,55,...,0,0,0,0,0,0,0,0,1,0