<a href="https://colab.research.google.com/github/Lalla-dev/ML-practice-projects/blob/main/nlp-emotion-detection-preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
df = pd.read_csv('/content/train.txt',header = None , names = ['text','emotions'], sep = ';')

In [65]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [66]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [67]:
df['emotions'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [68]:
emotions = df['emotions'].unique()
i = 0
for emo in emotions:
  df['emotions'] = df['emotions'].replace(emo,i)
  i +=1

df

/tmp/ipykernel_2548/374541393.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['emotions'] = df['emotions'].replace(emo,i)

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [69]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [70]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [71]:
df['text'].apply(remove_punc)

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

In [72]:
def remove_txt(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new += i
  return new
df['text'] = df['text'].apply(remove_txt)

In [73]:
def remove_emoji(emo):
  new =""
  for i in emo:
    if i.isascii():
      new += i
  return new
df['text'] = df['text'].apply(remove_emoji)
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [74]:
import nltk

In [75]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [76]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [77]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [78]:
len(stop_words)
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [79]:
def remove_sw(txt):
  words = txt.split()
  cleaned=[]
  for i in words:
    if i not in stop_words:
      cleaned.append(i)
  return " ".join(cleaned)

In [80]:
df['text'] = df['text'].apply(remove_sw)

In [81]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'